--- 
- hosts: all 
  become: true 
   vars:
    companyname: MithunTechnolgies
    location: Bangalore
  tasks: 
   - name: install apache HTTP server
     yum:
      name: httpd
      state: latest
   - name: Start the APache HTTP Server
     service: 
      name: httpd
      state: started
      enabled: true
   - name: copy index.html
     template:
      src: index.html
      dest: /var/www/html/index.html
...