--- 
- hosts: all 
  become: true 
  vars_files:
   - variable.yml
  tasks: 
   - name: install apache HTTP server
     yum:
      name: httpd
      state: latest
  
   - name: copy index.html
     template:
      src: index.html
      dest: /var/www/html/index.html
  nodify: 
   - Re-Start the APache HTTP Server
  handlers:
   - name: Re-Start the APache HTTP Server
     service: 
      name: httpd
      state: restarted
      enabled: true
...
